name: natsu
services:
  natsu:
    image: flustix/natsu:latest
    user: root # surely this is fine
    container_name: natsu-backend
    restart: unless-stopped
    volumes:
      - natsu:/files
    environment:
      - MONGO_CONNECTION=mongodb://localhost:27017
      - MONGO_DATABASE=natsu
      - FFMPEG_PATH=ffmpeg
    ports:
      - "6510:6510"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  natsu:
    name: natsu-storage