name: natsu

services:
  natsu:
    image: flustix/natsu:latest
    user: root # surely this is fine
    container_name: natsu-backend
    restart: unless-stopped
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASS=admin
      - SERVER_NAME=localhost
    volumes:
      - natsu:/files
    networks:
      - natsu
    labels:
      - com.centurylinklabs.watchtower.scope=natsu
    depends_on:
      - mongo

  web:
    image: flustix/natsu-web:latest
    container_name: natsu-web
    restart: unless-stopped
    ports:
      - "6511:80"
    networks:
      - natsu
    labels:
      - com.centurylinklabs.watchtower.scope=natsu

  mongo:
    image: mongo:latest
    container_name: natsu-db
    restart: unless-stopped
    volumes:
      - db:/data/db
      - db-config:/data/configdb
    networks:
      - natsu
    labels:
      - com.centurylinklabs.watchtower.scope=natsu
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet

  watchtower:
    container_name: natsu-watchtower
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope natsu --interval 900 --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  natsu:
    name: natsu-storage
  db:
    name: natsu-db
  db-config:
    name: natsu-db-config

networks:
  natsu:
    driver: bridge
    name: natsu-network